export const FUSOS = [
  { group: 'Brasil', value: 'America/Noronha', label: 'Fernando de Noronha (FNT, UTC-2)' },
  { group: 'Brasil', value: 'America/Belem', label: 'Belém (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Fortaleza', label: 'Fortaleza (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Recife', label: 'Recife (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Araguaina', label: 'Araguaína (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Maceio', label: 'Maceió (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Bahia', label: 'Salvador (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Sao_Paulo', label: 'Brasília (BRT, UTC-3)' },
  { group: 'Brasil', value: 'America/Santarem', label: 'Santarém (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Campo_Grande', label: 'Campo Grande (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Cuiaba', label: 'Cuiabá (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Porto_Velho', label: 'Porto Velho (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Boa_Vista', label: 'Boa Vista (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Manaus', label: 'Manaus (AMT, UTC-4)' },
  { group: 'Brasil', value: 'America/Eirunepe', label: 'Eirunepé (ACT, UTC-5)' },
  { group: 'Brasil', value: 'America/Rio_Branco', label: 'Rio Branco (ACT, UTC-5)' },
  { group: 'Outros', value: 'America/New_York', label: 'Nova York (EST)' },
  { group: 'Outros', value: 'Europe/London', label: 'Londres (GMT)' },
];
