# ===============================
# BANCO DE DADOS — POSTGRESQL LOCAL (Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/tempoclaroapp
spring.datasource.username=sci
spring.datasource.password=sci

spring.datasource.driver-class-name=org.postgresql.Driver

# Cria as tabelas e os seeds automaticamente no boot local
spring.sql.init.mode=always

# Porta local da API
server.port=8080

# Desativar docker-compose para usar o banco local já existente
spring.docker.compose.enabled=false

# ===============================
# HIKARI
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ===============================
# LOGS
# ===============================
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
