# ===============================
# BANCO DE DADOS POSTGRESQL NEON
# ===============================
spring.datasource.url=jdbc:postgresql://ep-super-leaf-ac3deoh9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_hQMvyaL2APs9
spring.datasource.driver-class-name=org.postgresql.Driver

# Inicialização do banco (Cria as tabelas usando schema.sql)
spring.sql.init.mode=always

# Porta dinâmica (se necessária pela plataforma cloud)
server.port=${PORT:8080}

# ===============================
# HIKARI
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
