# ===============================
# BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:h2:mem:backend_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always
server.port=8082
# ===============================
# DOKER
# ===============================
spring.docker.compose.readiness.wait=always
spring.docker.compose.enabled=false
# ===============================
# HIKARI
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
# ===============================
# LOGS
# ===============================
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate=DEBUG