
spring.datasource.url=jdbc:postgresql://db:5432/backend_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# Cria as tabelas e os seeds automaticamente no boot
spring.sql.init.mode=always

# Porta que o compose mapeia (8082:8082)
server.port=8082

# Desativa o docker-compose do Spring: o banco já sobe pelo compose.yaml
spring.docker.compose.enabled=false

# ===============================
# HIKARI
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ===============================
# LOGS
# ===============================
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
